from enum import StrEnum

class OriginsTypes(StrEnum):
    INTERNATIONAL = "international"
    CLUB = "club"

class FormatTypes(StrEnum):
    CTC = "CTC"
    BWT = "BWT"
    RHP = "RHP"
    IPT  = "IPT"
    HND = "HND"
    T20 = "T20"
    CCH = "CCH"
    SSH = "SSH"
    CPL = "CPL"
    IT20 = "IT20"
    PSL = "PSL"
    MSL = "MSL"
    IPO = "IPO"
    ODI = "ODI"
    ILT = "ILT"
    ODM = "ODM"
    WBB = "WBB"
    WCL = "WCL"
    BPL = "BPL"
    BBL = "BBL"
    MDM = "MDM"
    BLZ = "BLZ"
    SSM = "SSM"
    NTB = "NTB"
    LPL = "LPL"
    Test = "Test"
    FRB = "FRB"
    APL = "APL"
    RLC = "RLC"
    CEC = "CEC"
    SFT = "SFT"
    SAT = "SAT"
    WTC = "WTC"
    WSL = "WSL"